apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana
  labels:
    nfs: grafana
  namespace: monitoring
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    - nfsvers=4.1
  nfs:
    path: /media/pi/Elements/k8sNFS/grafana/
    server: 192.168.1.142
