apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-k8s-db-prometheus-k8s-0-pv
  labels:
    nfs: prometheus-k8s-db-prometheus-k8s-0
  namespace: monitoring
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  #storageClassName: slow
  nfs:
    path: /media/mybook/k8sNFS/prometheus/
    server: 192.168.1.142
